-- MySQL Script generated by MySQL Workbench
-- Fri Mar  8 09:27:36 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema crm_database
-- -----------------------------------------------------
-- Database for CRM-oppgaven - Gruppe 3

-- -----------------------------------------------------
-- Schema crm_database
--
-- Database for CRM-oppgaven - Gruppe 3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `crm_database` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `crm_database` ;

-- -----------------------------------------------------
-- Table `crm_database`.`postnummer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_database`.`postnummer` (
  `postnummer` VARCHAR(4) NOT NULL,
  `poststed` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`postnummer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_database`.`kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_database`.`kunde` (
  `kundeID` INT NOT NULL AUTO_INCREMENT,
  `navn` VARCHAR(45) NOT NULL,
  `epost` VARCHAR(100) NOT NULL,
  `tlf` VARCHAR(12) NOT NULL,
  `nettsted` VARCHAR(60) NULL,
  `postnummer` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`kundeID`),
  INDEX `fk_kunde_postSted1_idx` (`postnummer` ASC),
  CONSTRAINT `fk_kunde_postSted1`
    FOREIGN KEY (`postnummer`)
    REFERENCES `crm_database`.`postnummer` (`postnummer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `crm_database`.`kontaktperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `crm_database`.`kontaktperson` (
  `kontaktpersonID` INT NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(45) NOT NULL,
  `etternavn` VARCHAR(45) NOT NULL,
  `stilling` VARCHAR(80) NOT NULL,
  `avdeling` VARCHAR(80) NOT NULL,
  `tlf` VARCHAR(12) NOT NULL,
  `epost` VARCHAR(100) NOT NULL,
  `kundeID` INT NOT NULL,
  PRIMARY KEY (`kontaktpersonID`),
  INDEX `fk_kontaktperson_kunde1_idx` (`kundeID` ASC),
  CONSTRAINT `fk_kontaktperson_kunde1`
    FOREIGN KEY (`kundeID`)
    REFERENCES `crm_database`.`kunde` (`kundeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
